/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Sparkles, Zap, Snowflake, Ghost, Flame, Waves, Sun, Atom, Terminal, Wind, Cloud, Moon, Target, Activity } from 'lucide-react';
import { SimConfig } from '../types/simulation';

export interface Preset extends Partial<SimConfig> {
  label: string;
  icon: any;
}

export const PRESETS: Record<string, Preset> = {
  nebula: {
    label: 'Nebula',
    icon: Sparkles,
    gravity: 0,
    friction: 0.97,
    attraction: 8,
    repulsion: 0,
    particleLife: 200,
    particleSize: 2,
    vortex: true,
    flocking: true,
  },
  blackhole: {
    label: 'Black Hole',
    icon: Zap,
    gravity: 0,
    friction: 0.99,
    attraction: 30,
    repulsion: 0,
    particleLife: 400,
    particleSize: 1,
    vortex: true,
    flocking: false,
  },
  firestorm: {
    label: 'Firestorm',
    icon: Flame,
    gravity: -0.05,
    friction: 0.95,
    attraction: 0,
    repulsion: 12,
    particleLife: 80,
    particleSize: 5,
    vortex: false,
    flocking: false,
  },
  deepsea: {
    label: 'Deep Sea',
    icon: Waves,
    gravity: 0.02,
    friction: 0.92,
    attraction: 5,
    repulsion: 2,
    particleLife: 300,
    particleSize: 3,
    vortex: false,
    flocking: true,
  },
  supernova: {
    label: 'Supernova',
    icon: Sun,
    gravity: 0,
    friction: 0.98,
    attraction: 0,
    repulsion: 40,
    particleLife: 150,
    particleSize: 6,
    vortex: true,
    flocking: false,
  },
  quantum: {
    label: 'Quantum',
    icon: Atom,
    gravity: 0,
    friction: 1,
    attraction: 15,
    repulsion: 15,
    particleLife: 50,
    particleSize: 1.5,
    vortex: false,
    flocking: true,
  },
  matrix: {
    label: 'Matrix',
    icon: Terminal,
    gravity: 0.15,
    friction: 0.96,
    attraction: 0,
    repulsion: 0,
    particleLife: 250,
    particleSize: 2,
    vortex: false,
    flocking: true,
  },
  snow: {
    label: 'Blizzard',
    icon: Snowflake,
    gravity: 0.08,
    friction: 0.94,
    attraction: 0,
    repulsion: 5,
    particleLife: 120,
    particleSize: 4,
    vortex: false,
    flocking: false,
  },
  ghost: {
    label: 'Ethereal',
    icon: Ghost,
    gravity: -0.03,
    friction: 0.98,
    attraction: 3,
    repulsion: 15,
    particleLife: 180,
    particleSize: 3,
    vortex: false,
    flocking: true,
  },
  solar: {
    label: 'Solar Flare',
    icon: Wind,
    gravity: -0.01,
    friction: 0.99,
    attraction: 0,
    repulsion: 25,
    particleLife: 100,
    particleSize: 4,
    vortex: true,
    flocking: false,
  },
  void: {
    label: 'The Void',
    icon: Moon,
    gravity: 0,
    friction: 0.9,
    attraction: 50,
    repulsion: 0,
    particleLife: 500,
    particleSize: 1,
    vortex: false,
    flocking: false,
  },
  cyber: {
    label: 'Cyberpunk',
    icon: Activity,
    gravity: 0,
    friction: 0.95,
    attraction: 10,
    repulsion: 10,
    particleLife: 60,
    particleSize: 2,
    vortex: false,
    flocking: true,
  },
  monsoon: {
    label: 'Monsoon',
    icon: Cloud,
    gravity: 0.2,
    friction: 0.93,
    attraction: 0,
    repulsion: 2,
    particleLife: 150,
    particleSize: 2,
    vortex: false,
    flocking: true,
  },
  pulse: {
    label: 'Pulse',
    icon: Target,
    gravity: 0,
    friction: 0.98,
    attraction: 20,
    repulsion: 20,
    particleLife: 120,
    particleSize: 3,
    vortex: true,
    flocking: true,
  }
};
